server:
  port: 23328

spring:
  datasource:
    platform: h2
    username: dev
    password: dev
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./app.db
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath*:/mapper/*.xml
  #  type-aliases-package: dev.odes.demo.user
  #  config-location: classpath:mybatis-config.xml
  #  type-handlers-package: xyz.iotas.persist.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
    cache-enabled: false

#---
server:
  port: 23327

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/celerity?useUnicode=true&characterEncoding=utf8&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath*:/mapper/*.xml
  #  type-aliases-package: dev.odes.demo.user
  #  config-location: classpath:mybatis-config.xml
  #  type-handlers-package: xyz.iotas.persist.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
    cache-enabled: false
