server:
  port: 23328

spring:
  datasource:
    platform: h2
    username: dev
    password: dev
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./app.db
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
