server:
  port: 23328

spring:
  datasource:
    username: dev
    password: dev
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./app.db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath*:/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  #  type-aliases-package: dev.odes.demo.user
  #  type-handlers-package: dev.odes.persist.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
    cache-enabled: false
