server:
  port: 23328

spring:
  name: CelerityApp
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: 123456
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./celerity_app
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/celerity?useUnicode=true&characterEncoding=utf8&useSSL=false
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    show-sql: true
  #    hibernate:
  #      ddl-auto: update
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath*:/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
#  type-aliases-package: dev.odes.demo.user
#  type-handlers-package: dev.odes.persist.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
    cache-enabled: false
